version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: luizalabs_postgres
    environment:
      POSTGRES_USER: postgressUser
      POSTGRES_PASSWORD: postgressPass
      POSTGRES_DB: luizalabs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: luizalabs_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
